import { tenantQuery } from '../lib/db.mjs'
import { renderPDF } from '../shared/generate-pdf.mjs'
import { uploadBuffer } from '../lib/r2.mjs'

/**
 * Build an HTML document for the CV PDF combining report blocks and user CV data.
 *
 * @param {object} opts
 * @param {string} opts.cvMarkdown - User's CV in markdown
 * @param {string} opts.profileJson - User's profile as JSON string
 * @param {string} opts.reportContentMd - Evaluation report in markdown
 * @param {object} opts.blocksJson - Parsed evaluation blocks
 * @param {string} opts.jobTitle - Job title
 * @param {string} opts.company - Company name
 * @param {string} opts.jobUrl - Job URL
 */
function buildCVHtml({ cvMarkdown, profileJson, reportContentMd, blocksJson, jobTitle, company, jobUrl }) {
  let profile = {}
  try {
    profile = typeof profileJson === 'string' ? JSON.parse(profileJson) : (profileJson || {})
  } catch {
    profile = {}
  }

  const candidateName = profile.name || profile.full_name || 'Candidate'
  const overallScore = blocksJson?.blockA?.score
    ? Object.values(blocksJson)
        .filter(b => typeof b === 'object' && b !== null && typeof b.score === 'number')
        .reduce((acc, b, _, arr) => acc + b.score / arr.length, 0)
        .toFixed(1)
    : null

  // Convert markdown to basic HTML (simple approach — production would use a proper parser)
  const cvHtml = cvMarkdown
    .split('\n')
    .map(line => {
      if (line.startsWith('# ')) return `<h1>${escapeHtml(line.slice(2))}</h1>`
      if (line.startsWith('## ')) return `<h2>${escapeHtml(line.slice(3))}</h2>`
      if (line.startsWith('### ')) return `<h3>${escapeHtml(line.slice(4))}</h3>`
      if (line.startsWith('- ')) return `<li>${escapeHtml(line.slice(2))}</li>`
      if (line.startsWith('**') && line.endsWith('**')) return `<strong>${escapeHtml(line.slice(2, -2))}</strong><br>`
      if (line.trim() === '') return '<br>'
      return `<p>${escapeHtml(line)}</p>`
    })
    .join('\n')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CV — ${escapeHtml(candidateName)} — ${escapeHtml(jobTitle)} at ${escapeHtml(company)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, 'Helvetica Neue', Arial, sans-serif;
      font-size: 11pt;
      line-height: 1.5;
      color: #1a1a1a;
      background: #fff;
    }
    .header {
      border-bottom: 2px solid #2563eb;
      padding-bottom: 12px;
      margin-bottom: 20px;
    }
    .header h1 { font-size: 22pt; font-weight: 700; color: #111; }
    .job-target {
      background: #f0f7ff;
      border-left: 3px solid #2563eb;
      padding: 8px 12px;
      margin-bottom: 20px;
      font-size: 10pt;
    }
    .job-target strong { color: #2563eb; }
    .score-badge {
      display: inline-block;
      background: #2563eb;
      color: white;
      padding: 2px 8px;
      border-radius: 4px;
      font-size: 10pt;
      margin-left: 8px;
    }
    h1 { font-size: 16pt; margin: 16px 0 6px; color: #111; }
    h2 { font-size: 13pt; margin: 14px 0 4px; color: #222; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
    h3 { font-size: 11pt; margin: 10px 0 2px; color: #333; }
    p { margin: 4px 0; }
    li { margin: 2px 0 2px 16px; list-style-type: disc; }
    strong { font-weight: 600; }
    br { display: block; margin: 4px 0; }
    .footer {
      margin-top: 24px;
      padding-top: 12px;
      border-top: 1px solid #e5e7eb;
      font-size: 9pt;
      color: #6b7280;
      text-align: center;
    }
    @page { margin: 0.6in; }
  </style>
</head>
<body>
  <div class="job-target">
    <strong>Tailored for:</strong> ${escapeHtml(jobTitle)} at ${escapeHtml(company)}
    ${overallScore ? `<span class="score-badge">Score: ${overallScore}/5</span>` : ''}
    — <a href="${escapeHtml(jobUrl)}">${escapeHtml(jobUrl)}</a>
  </div>

  <div class="cv-content">
    ${cvHtml}
  </div>

  <div class="footer">
    Generated by career-ops · ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
  </div>
</body>
</html>`
}

function escapeHtml(str) {
  return String(str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

/**
 * Handle a "generate-pdf" pg-boss job.
 *
 * Payload: { user_id, job_id, application_id }
 *
 * Flow:
 *   1. Fetch report (content_md, blocks_json)
 *   2. Fetch job (title, company, url)
 *   3. Fetch user (cv_markdown, profile_json)
 *   4. Build HTML combining CV data + report blocks
 *   5. Call renderPDF(html) → Buffer
 *   6. Upload to R2 at key {user_id}/{job_id}/cv.pdf
 *   7. UPDATE applications.pdf_path with the R2 key
 *
 * @param {object} job - pg-boss job object
 * @param {object} job.data - Job payload
 */
export async function handleGeneratePDF(job) {
  const { user_id, job_id, application_id } = job.data

  // Fetch report
  const reportResult = await tenantQuery(
    user_id,
    `SELECT id, content_md, blocks_json FROM reports WHERE application_id = $1::uuid LIMIT 1`,
    [application_id]
  )
  const report = reportResult.rows[0] || {}

  // Fetch job
  const jobResult = await tenantQuery(
    user_id,
    `SELECT id, title, company, url FROM jobs WHERE id = $1::uuid LIMIT 1`,
    [job_id]
  )
  const jobData = jobResult.rows[0] || {}

  // Fetch user CV
  const userResult = await tenantQuery(
    user_id,
    `SELECT cv_markdown, profile_json FROM users WHERE id = $1::uuid LIMIT 1`,
    [user_id]
  )
  const user = userResult.rows[0] || {}

  // Parse blocks_json
  let blocksJson = {}
  try {
    blocksJson = typeof report.blocks_json === 'string'
      ? JSON.parse(report.blocks_json)
      : (report.blocks_json || {})
  } catch {
    blocksJson = {}
  }

  // Build HTML
  const htmlContent = buildCVHtml({
    cvMarkdown: user.cv_markdown || '',
    profileJson: user.profile_json || '{}',
    reportContentMd: report.content_md || '',
    blocksJson,
    jobTitle: jobData.title || '',
    company: jobData.company || '',
    jobUrl: jobData.url || '',
  })

  // Render PDF
  const pdfBuffer = await renderPDF(htmlContent)

  // Upload to R2 at key {user_id}/{job_id}/cv.pdf
  const key = `${user_id}/${job_id}/cv.pdf`
  await uploadBuffer(key, pdfBuffer, 'application/pdf')

  // UPDATE applications.pdf_path
  await tenantQuery(
    user_id,
    `UPDATE applications SET pdf_path = $1 WHERE id = $2::uuid AND user_id = $3::uuid`,
    [key, application_id, user_id]
  )
}
