// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getApplicationByJobID = `-- name: GetApplicationByJobID :one
SELECT id, user_id, job_id, score, status, notes, pdf_path, created_at, updated_at FROM applications
WHERE job_id = $1
LIMIT 1
`

func (q *Queries) GetApplicationByJobID(ctx context.Context, jobID uuid.UUID) (Application, error) {
	row := q.db.QueryRowContext(ctx, getApplicationByJobID, jobID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.Score,
		&i.Status,
		&i.Notes,
		&i.PdfPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertApplication = `-- name: InsertApplication :one
INSERT INTO applications (
  user_id,
  job_id,
  score,
  status
) VALUES (
  $1, $2, $3, $4
) RETURNING id, user_id, job_id, score, status, notes, pdf_path, created_at, updated_at
`

type InsertApplicationParams struct {
	UserID uuid.UUID       `json:"user_id"`
	JobID  uuid.UUID       `json:"job_id"`
	Score  sql.NullFloat64 `json:"score"`
	Status AppStatusT      `json:"status"`
}

func (q *Queries) InsertApplication(ctx context.Context, arg InsertApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, insertApplication,
		arg.UserID,
		arg.JobID,
		arg.Score,
		arg.Status,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.Score,
		&i.Status,
		&i.Notes,
		&i.PdfPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplicationsByUser = `-- name: ListApplicationsByUser :many
SELECT id, user_id, job_id, score, status, notes, pdf_path, created_at, updated_at FROM applications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListApplicationsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListApplicationsByUser(ctx context.Context, arg ListApplicationsByUserParams) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, listApplicationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JobID,
			&i.Score,
			&i.Status,
			&i.Notes,
			&i.PdfPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplicationNotes = `-- name: UpdateApplicationNotes :one
UPDATE applications
SET notes      = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, job_id, score, status, notes, pdf_path, created_at, updated_at
`

type UpdateApplicationNotesParams struct {
	ID    uuid.UUID      `json:"id"`
	Notes sql.NullString `json:"notes"`
}

func (q *Queries) UpdateApplicationNotes(ctx context.Context, arg UpdateApplicationNotesParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, updateApplicationNotes, arg.ID, arg.Notes)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.Score,
		&i.Status,
		&i.Notes,
		&i.PdfPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApplicationPDFPath = `-- name: UpdateApplicationPDFPath :one
UPDATE applications
SET pdf_path   = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, job_id, score, status, notes, pdf_path, created_at, updated_at
`

type UpdateApplicationPDFPathParams struct {
	ID      uuid.UUID      `json:"id"`
	PdfPath sql.NullString `json:"pdf_path"`
}

func (q *Queries) UpdateApplicationPDFPath(ctx context.Context, arg UpdateApplicationPDFPathParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, updateApplicationPDFPath, arg.ID, arg.PdfPath)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.Score,
		&i.Status,
		&i.Notes,
		&i.PdfPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApplicationStatus = `-- name: UpdateApplicationStatus :one
UPDATE applications
SET status     = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, job_id, score, status, notes, pdf_path, created_at, updated_at
`

type UpdateApplicationStatusParams struct {
	ID     uuid.UUID  `json:"id"`
	Status AppStatusT `json:"status"`
}

func (q *Queries) UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, updateApplicationStatus, arg.ID, arg.Status)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.Score,
		&i.Status,
		&i.Notes,
		&i.PdfPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
