// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: article_digests.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteDigest = `-- name: DeleteDigest :execrows
DELETE FROM article_digests
WHERE id = $1 AND user_id = $2
`

type DeleteDigestParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDigest(ctx context.Context, arg DeleteDigestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDigest, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertDigest = `-- name: InsertDigest :one
INSERT INTO article_digests (
  user_id,
  title,
  content_md
) VALUES (
  $1, $2, $3
) RETURNING id, user_id, title, content_md, created_at
`

type InsertDigestParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Title     string    `json:"title"`
	ContentMd string    `json:"content_md"`
}

func (q *Queries) InsertDigest(ctx context.Context, arg InsertDigestParams) (ArticleDigest, error) {
	row := q.db.QueryRowContext(ctx, insertDigest, arg.UserID, arg.Title, arg.ContentMd)
	var i ArticleDigest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.ContentMd,
		&i.CreatedAt,
	)
	return i, err
}

const listDigestsByUser = `-- name: ListDigestsByUser :many
SELECT id, user_id, title, content_md, created_at FROM article_digests
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDigestsByUser(ctx context.Context, userID uuid.UUID) ([]ArticleDigest, error) {
	rows, err := q.db.QueryContext(ctx, listDigestsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArticleDigest
	for rows.Next() {
		var i ArticleDigest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.ContentMd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
