// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies_catalog.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getCompaniesCatalogByID = `-- name: GetCompaniesCatalogByID :one
SELECT id, name, careers_url, provider_id, ats_api_url, created_at FROM companies_catalog
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCompaniesCatalogByID(ctx context.Context, id uuid.UUID) (CompaniesCatalog, error) {
	row := q.db.QueryRowContext(ctx, getCompaniesCatalogByID, id)
	var i CompaniesCatalog
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CareersUrl,
		&i.ProviderID,
		&i.AtsApiUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listCompaniesCatalog = `-- name: ListCompaniesCatalog :many
SELECT id, name, careers_url, provider_id, ats_api_url, created_at FROM companies_catalog
ORDER BY name ASC
`

func (q *Queries) ListCompaniesCatalog(ctx context.Context) ([]CompaniesCatalog, error) {
	rows, err := q.db.QueryContext(ctx, listCompaniesCatalog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompaniesCatalog
	for rows.Next() {
		var i CompaniesCatalog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CareersUrl,
			&i.ProviderID,
			&i.AtsApiUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
