// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cv_ingestions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getCVIngestion = `-- name: GetCVIngestion :one
SELECT id, user_id, status, started_at, finished_at FROM cv_ingestions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCVIngestion(ctx context.Context, id uuid.UUID) (CvIngestion, error) {
	row := q.db.QueryRowContext(ctx, getCVIngestion, id)
	var i CvIngestion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertCVIngestion = `-- name: InsertCVIngestion :one
INSERT INTO cv_ingestions (user_id) VALUES ($1) RETURNING id, user_id, status, started_at, finished_at
`

func (q *Queries) InsertCVIngestion(ctx context.Context, userID uuid.UUID) (CvIngestion, error) {
	row := q.db.QueryRowContext(ctx, insertCVIngestion, userID)
	var i CvIngestion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateCVIngestionStatus = `-- name: UpdateCVIngestionStatus :one
UPDATE cv_ingestions
SET status = $2,
    finished_at = CASE WHEN $2 IN ('completed', 'failed') THEN now() ELSE finished_at END
WHERE id = $1
RETURNING id, user_id, status, started_at, finished_at
`

type UpdateCVIngestionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateCVIngestionStatus(ctx context.Context, arg UpdateCVIngestionStatusParams) (CvIngestion, error) {
	row := q.db.QueryRowContext(ctx, updateCVIngestionStatus, arg.ID, arg.Status)
	var i CvIngestion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
