// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cvs.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getMasterCVByUser = `-- name: GetMasterCVByUser :one
SELECT id, user_id, title, content_md, is_master, created_at FROM cvs
WHERE user_id  = $1
  AND is_master = true
LIMIT 1
`

func (q *Queries) GetMasterCVByUser(ctx context.Context, userID uuid.UUID) (Cv, error) {
	row := q.db.QueryRowContext(ctx, getMasterCVByUser, userID)
	var i Cv
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.ContentMd,
		&i.IsMaster,
		&i.CreatedAt,
	)
	return i, err
}

const insertCV = `-- name: InsertCV :one
INSERT INTO cvs (
  user_id,
  title,
  content_md,
  is_master
) VALUES (
  $1, $2, $3, $4
) RETURNING id, user_id, title, content_md, is_master, created_at
`

type InsertCVParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Title     string    `json:"title"`
	ContentMd string    `json:"content_md"`
	IsMaster  bool      `json:"is_master"`
}

func (q *Queries) InsertCV(ctx context.Context, arg InsertCVParams) (Cv, error) {
	row := q.db.QueryRowContext(ctx, insertCV,
		arg.UserID,
		arg.Title,
		arg.ContentMd,
		arg.IsMaster,
	)
	var i Cv
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.ContentMd,
		&i.IsMaster,
		&i.CreatedAt,
	)
	return i, err
}

const listCVsByUser = `-- name: ListCVsByUser :many
SELECT id, user_id, title, content_md, is_master, created_at FROM cvs
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCVsByUser(ctx context.Context, userID uuid.UUID) ([]Cv, error) {
	rows, err := q.db.QueryContext(ctx, listCVsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cv
	for rows.Next() {
		var i Cv
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.ContentMd,
			&i.IsMaster,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMasterCV = `-- name: SetMasterCV :exec
UPDATE cvs
SET is_master = (id = $1)
WHERE user_id = $2
`

type SetMasterCVParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Clear the current master then set the new one (two statements — call in a tx)
func (q *Queries) SetMasterCV(ctx context.Context, arg SetMasterCVParams) error {
	_, err := q.db.ExecContext(ctx, setMasterCV, arg.ID, arg.UserID)
	return err
}

const updateCV = `-- name: UpdateCV :one
UPDATE cvs
SET title      = $2,
    content_md = $3
WHERE id = $1
RETURNING id, user_id, title, content_md, is_master, created_at
`

type UpdateCVParams struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	ContentMd string    `json:"content_md"`
}

func (q *Queries) UpdateCV(ctx context.Context, arg UpdateCVParams) (Cv, error) {
	row := q.db.QueryRowContext(ctx, updateCV, arg.ID, arg.Title, arg.ContentMd)
	var i Cv
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.ContentMd,
		&i.IsMaster,
		&i.CreatedAt,
	)
	return i, err
}
