// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_ingest_runs.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const appendEmailIngestRunError = `-- name: AppendEmailIngestRunError :one
UPDATE email_ingest_runs
SET errors_json = errors_json || $2::jsonb
WHERE id = $1
RETURNING id, user_id, status, new_jobs, errors_json, started_at, finished_at
`

type AppendEmailIngestRunErrorParams struct {
	ID      uuid.UUID       `json:"id"`
	Column2 json.RawMessage `json:"column_2"`
}

func (q *Queries) AppendEmailIngestRunError(ctx context.Context, arg AppendEmailIngestRunErrorParams) (EmailIngestRun, error) {
	row := q.db.QueryRowContext(ctx, appendEmailIngestRunError, arg.ID, arg.Column2)
	var i EmailIngestRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.NewJobs,
		&i.ErrorsJson,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getEmailIngestRunByID = `-- name: GetEmailIngestRunByID :one
SELECT id, user_id, status, new_jobs, errors_json, started_at, finished_at FROM email_ingest_runs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetEmailIngestRunByID(ctx context.Context, id uuid.UUID) (EmailIngestRun, error) {
	row := q.db.QueryRowContext(ctx, getEmailIngestRunByID, id)
	var i EmailIngestRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.NewJobs,
		&i.ErrorsJson,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertEmailIngestRun = `-- name: InsertEmailIngestRun :one
INSERT INTO email_ingest_runs (user_id)
VALUES ($1)
RETURNING id, user_id, status, new_jobs, errors_json, started_at, finished_at
`

func (q *Queries) InsertEmailIngestRun(ctx context.Context, userID uuid.UUID) (EmailIngestRun, error) {
	row := q.db.QueryRowContext(ctx, insertEmailIngestRun, userID)
	var i EmailIngestRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.NewJobs,
		&i.ErrorsJson,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateEmailIngestRunNewJobs = `-- name: UpdateEmailIngestRunNewJobs :one
UPDATE email_ingest_runs
SET new_jobs = new_jobs + $2
WHERE id = $1
RETURNING id, user_id, status, new_jobs, errors_json, started_at, finished_at
`

type UpdateEmailIngestRunNewJobsParams struct {
	ID      uuid.UUID `json:"id"`
	NewJobs int32     `json:"new_jobs"`
}

func (q *Queries) UpdateEmailIngestRunNewJobs(ctx context.Context, arg UpdateEmailIngestRunNewJobsParams) (EmailIngestRun, error) {
	row := q.db.QueryRowContext(ctx, updateEmailIngestRunNewJobs, arg.ID, arg.NewJobs)
	var i EmailIngestRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.NewJobs,
		&i.ErrorsJson,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateEmailIngestRunStatus = `-- name: UpdateEmailIngestRunStatus :one
UPDATE email_ingest_runs
SET status      = $2,
    finished_at = now()
WHERE id = $1
RETURNING id, user_id, status, new_jobs, errors_json, started_at, finished_at
`

type UpdateEmailIngestRunStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateEmailIngestRunStatus(ctx context.Context, arg UpdateEmailIngestRunStatusParams) (EmailIngestRun, error) {
	row := q.db.QueryRowContext(ctx, updateEmailIngestRunStatus, arg.ID, arg.Status)
	var i EmailIngestRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.NewJobs,
		&i.ErrorsJson,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
