// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const getJobByID = `-- name: GetJobByID :one
SELECT id, user_id, title, company, url, platform, status, scraped_content, evaluation_json, received_at, created_at FROM jobs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetJobByID(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Company,
		&i.Url,
		&i.Platform,
		&i.Status,
		&i.ScrapedContent,
		&i.EvaluationJson,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO jobs (
  user_id,
  title,
  company,
  url,
  platform,
  status,
  scraped_content,
  received_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, user_id, title, company, url, platform, status, scraped_content, evaluation_json, received_at, created_at
`

type InsertJobParams struct {
	UserID         uuid.UUID      `json:"user_id"`
	Title          string         `json:"title"`
	Company        string         `json:"company"`
	Url            string         `json:"url"`
	Platform       sql.NullString `json:"platform"`
	Status         JobStatusT     `json:"status"`
	ScrapedContent sql.NullString `json:"scraped_content"`
	ReceivedAt     sql.NullTime   `json:"received_at"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, insertJob,
		arg.UserID,
		arg.Title,
		arg.Company,
		arg.Url,
		arg.Platform,
		arg.Status,
		arg.ScrapedContent,
		arg.ReceivedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Company,
		&i.Url,
		&i.Platform,
		&i.Status,
		&i.ScrapedContent,
		&i.EvaluationJson,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listJobsByUser = `-- name: ListJobsByUser :many
SELECT id, user_id, title, company, url, platform, status, scraped_content, evaluation_json, received_at, created_at FROM jobs
WHERE user_id = $1
ORDER BY received_at DESC NULLS LAST, created_at DESC
LIMIT $2
OFFSET $3
`

type ListJobsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListJobsByUser(ctx context.Context, arg ListJobsByUserParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Company,
			&i.Url,
			&i.Platform,
			&i.Status,
			&i.ScrapedContent,
			&i.EvaluationJson,
			&i.ReceivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobEvaluationJSON = `-- name: UpdateJobEvaluationJSON :one
UPDATE jobs
SET evaluation_json = $2,
    status          = 'evaluated'
WHERE id = $1
RETURNING id, user_id, title, company, url, platform, status, scraped_content, evaluation_json, received_at, created_at
`

type UpdateJobEvaluationJSONParams struct {
	ID             uuid.UUID             `json:"id"`
	EvaluationJson pqtype.NullRawMessage `json:"evaluation_json"`
}

func (q *Queries) UpdateJobEvaluationJSON(ctx context.Context, arg UpdateJobEvaluationJSONParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, updateJobEvaluationJSON, arg.ID, arg.EvaluationJson)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Company,
		&i.Url,
		&i.Platform,
		&i.Status,
		&i.ScrapedContent,
		&i.EvaluationJson,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs
SET status = $2
WHERE id = $1
RETURNING id, user_id, title, company, url, platform, status, scraped_content, evaluation_json, received_at, created_at
`

type UpdateJobStatusParams struct {
	ID     uuid.UUID  `json:"id"`
	Status JobStatusT `json:"status"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, updateJobStatus, arg.ID, arg.Status)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Company,
		&i.Url,
		&i.Platform,
		&i.Status,
		&i.ScrapedContent,
		&i.EvaluationJson,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertJobByURL = `-- name: UpsertJobByURL :one
INSERT INTO jobs (
  user_id,
  title,
  company,
  url,
  platform,
  status,
  scraped_content,
  received_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
) ON CONFLICT (user_id, url) DO UPDATE
  SET title           = EXCLUDED.title,
      company         = EXCLUDED.company,
      platform        = EXCLUDED.platform,
      scraped_content = EXCLUDED.scraped_content,
      received_at     = EXCLUDED.received_at
RETURNING id, user_id, title, company, url, platform, status, scraped_content, evaluation_json, received_at, created_at
`

type UpsertJobByURLParams struct {
	UserID         uuid.UUID      `json:"user_id"`
	Title          string         `json:"title"`
	Company        string         `json:"company"`
	Url            string         `json:"url"`
	Platform       sql.NullString `json:"platform"`
	Status         JobStatusT     `json:"status"`
	ScrapedContent sql.NullString `json:"scraped_content"`
	ReceivedAt     sql.NullTime   `json:"received_at"`
}

func (q *Queries) UpsertJobByURL(ctx context.Context, arg UpsertJobByURLParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, upsertJobByURL,
		arg.UserID,
		arg.Title,
		arg.Company,
		arg.Url,
		arg.Platform,
		arg.Status,
		arg.ScrapedContent,
		arg.ReceivedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Company,
		&i.Url,
		&i.Platform,
		&i.Status,
		&i.ScrapedContent,
		&i.EvaluationJson,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}
