// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AppStatusT string

const (
	AppStatusTEvaluated AppStatusT = "Evaluated"
	AppStatusTApplied   AppStatusT = "Applied"
	AppStatusTResponded AppStatusT = "Responded"
	AppStatusTInterview AppStatusT = "Interview"
	AppStatusTOffer     AppStatusT = "Offer"
	AppStatusTRejected  AppStatusT = "Rejected"
	AppStatusTDiscarded AppStatusT = "Discarded"
	AppStatusTSKIP      AppStatusT = "SKIP"
)

func (e *AppStatusT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppStatusT(s)
	case string:
		*e = AppStatusT(s)
	default:
		return fmt.Errorf("unsupported scan type for AppStatusT: %T", src)
	}
	return nil
}

type NullAppStatusT struct {
	AppStatusT AppStatusT `json:"app_status_t"`
	Valid      bool       `json:"valid"` // Valid is true if AppStatusT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppStatusT) Scan(value interface{}) error {
	if value == nil {
		ns.AppStatusT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppStatusT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppStatusT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppStatusT), nil
}

type JobStatusT string

const (
	JobStatusTNew       JobStatusT = "new"
	JobStatusTScanned   JobStatusT = "scanned"
	JobStatusTEvaluated JobStatusT = "evaluated"
	JobStatusTArchived  JobStatusT = "archived"
)

func (e *JobStatusT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatusT(s)
	case string:
		*e = JobStatusT(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatusT: %T", src)
	}
	return nil
}

type NullJobStatusT struct {
	JobStatusT JobStatusT `json:"job_status_t"`
	Valid      bool       `json:"valid"` // Valid is true if JobStatusT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatusT) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatusT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatusT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatusT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatusT), nil
}

type PlanT string

const (
	PlanTFree      PlanT = "free"
	PlanTPro       PlanT = "pro"
	PlanTUnlimited PlanT = "unlimited"
)

func (e *PlanT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlanT(s)
	case string:
		*e = PlanT(s)
	default:
		return fmt.Errorf("unsupported scan type for PlanT: %T", src)
	}
	return nil
}

type NullPlanT struct {
	PlanT PlanT `json:"plan_t"`
	Valid bool  `json:"valid"` // Valid is true if PlanT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlanT) Scan(value interface{}) error {
	if value == nil {
		ns.PlanT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlanT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlanT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlanT), nil
}

type ScanStatusT string

const (
	ScanStatusTRunning   ScanStatusT = "running"
	ScanStatusTCompleted ScanStatusT = "completed"
	ScanStatusTPartial   ScanStatusT = "partial"
	ScanStatusTFailed    ScanStatusT = "failed"
)

func (e *ScanStatusT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScanStatusT(s)
	case string:
		*e = ScanStatusT(s)
	default:
		return fmt.Errorf("unsupported scan type for ScanStatusT: %T", src)
	}
	return nil
}

type NullScanStatusT struct {
	ScanStatusT ScanStatusT `json:"scan_status_t"`
	Valid       bool        `json:"valid"` // Valid is true if ScanStatusT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScanStatusT) Scan(value interface{}) error {
	if value == nil {
		ns.ScanStatusT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScanStatusT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScanStatusT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScanStatusT), nil
}

type Application struct {
	ID        uuid.UUID       `json:"id"`
	UserID    uuid.UUID       `json:"user_id"`
	JobID     uuid.UUID       `json:"job_id"`
	Score     sql.NullFloat64 `json:"score"`
	Status    AppStatusT      `json:"status"`
	Notes     sql.NullString  `json:"notes"`
	PdfPath   sql.NullString  `json:"pdf_path"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type ArticleDigest struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Title     string    `json:"title"`
	ContentMd string    `json:"content_md"`
	CreatedAt time.Time `json:"created_at"`
}

type CompaniesCatalog struct {
	ID         uuid.UUID      `json:"id"`
	Name       string         `json:"name"`
	CareersUrl string         `json:"careers_url"`
	ProviderID string         `json:"provider_id"`
	AtsApiUrl  sql.NullString `json:"ats_api_url"`
	CreatedAt  time.Time      `json:"created_at"`
}

type Cv struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Title     string    `json:"title"`
	ContentMd string    `json:"content_md"`
	IsMaster  bool      `json:"is_master"`
	CreatedAt time.Time `json:"created_at"`
}

type CvIngestion struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	Status     string       `json:"status"`
	StartedAt  time.Time    `json:"started_at"`
	FinishedAt sql.NullTime `json:"finished_at"`
}

type EmailIngestRun struct {
	ID         uuid.UUID       `json:"id"`
	UserID     uuid.UUID       `json:"user_id"`
	Status     string          `json:"status"`
	NewJobs    int32           `json:"new_jobs"`
	ErrorsJson json.RawMessage `json:"errors_json"`
	StartedAt  time.Time       `json:"started_at"`
	FinishedAt sql.NullTime    `json:"finished_at"`
}

type Job struct {
	ID             uuid.UUID             `json:"id"`
	UserID         uuid.UUID             `json:"user_id"`
	Title          string                `json:"title"`
	Company        string                `json:"company"`
	Url            string                `json:"url"`
	Platform       sql.NullString        `json:"platform"`
	Status         JobStatusT            `json:"status"`
	ScrapedContent sql.NullString        `json:"scraped_content"`
	EvaluationJson pqtype.NullRawMessage `json:"evaluation_json"`
	ReceivedAt     sql.NullTime          `json:"received_at"`
	CreatedAt      time.Time             `json:"created_at"`
}

type ProfileEdit struct {
	ID         uuid.UUID             `json:"id"`
	UserID     uuid.UUID             `json:"user_id"`
	FieldPath  string                `json:"field_path"`
	OldValue   pqtype.NullRawMessage `json:"old_value"`
	NewValue   pqtype.NullRawMessage `json:"new_value"`
	Source     string                `json:"source"`
	Status     string                `json:"status"`
	CreatedAt  time.Time             `json:"created_at"`
	ResolvedAt sql.NullTime          `json:"resolved_at"`
}

type Report struct {
	ID            uuid.UUID       `json:"id"`
	UserID        uuid.UUID       `json:"user_id"`
	ApplicationID uuid.UUID       `json:"application_id"`
	ContentMd     string          `json:"content_md"`
	BlocksJson    json.RawMessage `json:"blocks_json"`
	CreatedAt     time.Time       `json:"created_at"`
}

type ScanRun struct {
	ID         uuid.UUID       `json:"id"`
	UserID     uuid.UUID       `json:"user_id"`
	StartedAt  time.Time       `json:"started_at"`
	FinishedAt sql.NullTime    `json:"finished_at"`
	NewJobs    int32           `json:"new_jobs"`
	ErrorsJson json.RawMessage `json:"errors_json"`
	Status     ScanStatusT     `json:"status"`
}

type Usage struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	Month            string    `json:"month"`
	EvaluationsCount int32     `json:"evaluations_count"`
	PdfsCount        int32     `json:"pdfs_count"`
	IngestionsCount  int32     `json:"ingestions_count"`
}

type User struct {
	ID                 uuid.UUID       `json:"id"`
	Email              string          `json:"email"`
	GoogleID           string          `json:"google_id"`
	Plan               PlanT           `json:"plan"`
	CvMarkdown         sql.NullString  `json:"cv_markdown"`
	ProfileJson        json.RawMessage `json:"profile_json"`
	ProfileOverrides   json.RawMessage `json:"profile_overrides"`
	CreatedAt          time.Time       `json:"created_at"`
	GoogleRefreshToken sql.NullString  `json:"google_refresh_token"`
}

type WatchedCompany struct {
	ID         uuid.UUID      `json:"id"`
	UserID     uuid.UUID      `json:"user_id"`
	Name       string         `json:"name"`
	CareersUrl sql.NullString `json:"careers_url"`
	ProviderID sql.NullString `json:"provider_id"`
	AtsApiUrl  sql.NullString `json:"ats_api_url"`
	Enabled    bool           `json:"enabled"`
	CompanyID  uuid.NullUUID  `json:"company_id"`
	CreatedAt  time.Time      `json:"created_at"`
}
