// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile_edits.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const getProfileEdit = `-- name: GetProfileEdit :one
SELECT id, user_id, field_path, old_value, new_value, source, status, created_at, resolved_at FROM profile_edits
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProfileEdit(ctx context.Context, id uuid.UUID) (ProfileEdit, error) {
	row := q.db.QueryRowContext(ctx, getProfileEdit, id)
	var i ProfileEdit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FieldPath,
		&i.OldValue,
		&i.NewValue,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const insertProfileEdit = `-- name: InsertProfileEdit :one
INSERT INTO profile_edits (user_id, field_path, old_value, new_value, source, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, field_path, old_value, new_value, source, status, created_at, resolved_at
`

type InsertProfileEditParams struct {
	UserID    uuid.UUID             `json:"user_id"`
	FieldPath string                `json:"field_path"`
	OldValue  pqtype.NullRawMessage `json:"old_value"`
	NewValue  pqtype.NullRawMessage `json:"new_value"`
	Source    string                `json:"source"`
	Status    string                `json:"status"`
}

func (q *Queries) InsertProfileEdit(ctx context.Context, arg InsertProfileEditParams) (ProfileEdit, error) {
	row := q.db.QueryRowContext(ctx, insertProfileEdit,
		arg.UserID,
		arg.FieldPath,
		arg.OldValue,
		arg.NewValue,
		arg.Source,
		arg.Status,
	)
	var i ProfileEdit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FieldPath,
		&i.OldValue,
		&i.NewValue,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listProfileEditsByUser = `-- name: ListProfileEditsByUser :many
SELECT id, user_id, field_path, old_value, new_value, source, status, created_at, resolved_at FROM profile_edits
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProfileEditsByUser(ctx context.Context, userID uuid.UUID) ([]ProfileEdit, error) {
	rows, err := q.db.QueryContext(ctx, listProfileEditsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProfileEdit
	for rows.Next() {
		var i ProfileEdit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FieldPath,
			&i.OldValue,
			&i.NewValue,
			&i.Source,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProfileEditUndone = `-- name: MarkProfileEditUndone :one
UPDATE profile_edits
SET status = 'undone', resolved_at = NOW()
WHERE id = $1
RETURNING id, user_id, field_path, old_value, new_value, source, status, created_at, resolved_at
`

func (q *Queries) MarkProfileEditUndone(ctx context.Context, id uuid.UUID) (ProfileEdit, error) {
	row := q.db.QueryRowContext(ctx, markProfileEditUndone, id)
	var i ProfileEdit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FieldPath,
		&i.OldValue,
		&i.NewValue,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}
