// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getReportByApplicationID = `-- name: GetReportByApplicationID :one
SELECT id, user_id, application_id, content_md, blocks_json, created_at FROM reports
WHERE application_id = $1
LIMIT 1
`

func (q *Queries) GetReportByApplicationID(ctx context.Context, applicationID uuid.UUID) (Report, error) {
	row := q.db.QueryRowContext(ctx, getReportByApplicationID, applicationID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicationID,
		&i.ContentMd,
		&i.BlocksJson,
		&i.CreatedAt,
	)
	return i, err
}

const insertReport = `-- name: InsertReport :one
INSERT INTO reports (
  user_id,
  application_id,
  content_md,
  blocks_json
) VALUES (
  $1, $2, $3, $4
) RETURNING id, user_id, application_id, content_md, blocks_json, created_at
`

type InsertReportParams struct {
	UserID        uuid.UUID       `json:"user_id"`
	ApplicationID uuid.UUID       `json:"application_id"`
	ContentMd     string          `json:"content_md"`
	BlocksJson    json.RawMessage `json:"blocks_json"`
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, insertReport,
		arg.UserID,
		arg.ApplicationID,
		arg.ContentMd,
		arg.BlocksJson,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicationID,
		&i.ContentMd,
		&i.BlocksJson,
		&i.CreatedAt,
	)
	return i, err
}
