// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scan_runs.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const appendScanRunError = `-- name: AppendScanRunError :one
UPDATE scan_runs
SET errors_json = errors_json || $2::jsonb
WHERE id = $1
RETURNING id, user_id, started_at, finished_at, new_jobs, errors_json, status
`

type AppendScanRunErrorParams struct {
	ID      uuid.UUID       `json:"id"`
	Column2 json.RawMessage `json:"column_2"`
}

func (q *Queries) AppendScanRunError(ctx context.Context, arg AppendScanRunErrorParams) (ScanRun, error) {
	row := q.db.QueryRowContext(ctx, appendScanRunError, arg.ID, arg.Column2)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.NewJobs,
		&i.ErrorsJson,
		&i.Status,
	)
	return i, err
}

const getScanRunByID = `-- name: GetScanRunByID :one
SELECT id, user_id, started_at, finished_at, new_jobs, errors_json, status FROM scan_runs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetScanRunByID(ctx context.Context, id uuid.UUID) (ScanRun, error) {
	row := q.db.QueryRowContext(ctx, getScanRunByID, id)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.NewJobs,
		&i.ErrorsJson,
		&i.Status,
	)
	return i, err
}

const insertScanRun = `-- name: InsertScanRun :one
INSERT INTO scan_runs (user_id)
VALUES ($1)
RETURNING id, user_id, started_at, finished_at, new_jobs, errors_json, status
`

func (q *Queries) InsertScanRun(ctx context.Context, userID uuid.UUID) (ScanRun, error) {
	row := q.db.QueryRowContext(ctx, insertScanRun, userID)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.NewJobs,
		&i.ErrorsJson,
		&i.Status,
	)
	return i, err
}

const updateScanRunNewJobs = `-- name: UpdateScanRunNewJobs :one
UPDATE scan_runs
SET new_jobs = new_jobs + $2
WHERE id = $1
RETURNING id, user_id, started_at, finished_at, new_jobs, errors_json, status
`

type UpdateScanRunNewJobsParams struct {
	ID      uuid.UUID `json:"id"`
	NewJobs int32     `json:"new_jobs"`
}

func (q *Queries) UpdateScanRunNewJobs(ctx context.Context, arg UpdateScanRunNewJobsParams) (ScanRun, error) {
	row := q.db.QueryRowContext(ctx, updateScanRunNewJobs, arg.ID, arg.NewJobs)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.NewJobs,
		&i.ErrorsJson,
		&i.Status,
	)
	return i, err
}

const updateScanRunStatus = `-- name: UpdateScanRunStatus :one
UPDATE scan_runs
SET status      = $2,
    finished_at = now()
WHERE id = $1
RETURNING id, user_id, started_at, finished_at, new_jobs, errors_json, status
`

type UpdateScanRunStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status ScanStatusT `json:"status"`
}

func (q *Queries) UpdateScanRunStatus(ctx context.Context, arg UpdateScanRunStatusParams) (ScanRun, error) {
	row := q.db.QueryRowContext(ctx, updateScanRunStatus, arg.ID, arg.Status)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.NewJobs,
		&i.ErrorsJson,
		&i.Status,
	)
	return i, err
}
