// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUsageByUserMonth = `-- name: GetUsageByUserMonth :one
SELECT id, user_id, month, evaluations_count, pdfs_count, ingestions_count FROM usage
WHERE user_id = $1
  AND month   = $2
LIMIT 1
`

type GetUsageByUserMonthParams struct {
	UserID uuid.UUID `json:"user_id"`
	Month  string    `json:"month"`
}

func (q *Queries) GetUsageByUserMonth(ctx context.Context, arg GetUsageByUserMonthParams) (Usage, error) {
	row := q.db.QueryRowContext(ctx, getUsageByUserMonth, arg.UserID, arg.Month)
	var i Usage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.EvaluationsCount,
		&i.PdfsCount,
		&i.IngestionsCount,
	)
	return i, err
}

const upsertIncrementEvaluations = `-- name: UpsertIncrementEvaluations :one
INSERT INTO usage (user_id, month, evaluations_count)
VALUES ($1, $2, 1)
ON CONFLICT (user_id, month) DO UPDATE
  SET evaluations_count = usage.evaluations_count + 1
RETURNING id, user_id, month, evaluations_count, pdfs_count, ingestions_count
`

type UpsertIncrementEvaluationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Month  string    `json:"month"`
}

func (q *Queries) UpsertIncrementEvaluations(ctx context.Context, arg UpsertIncrementEvaluationsParams) (Usage, error) {
	row := q.db.QueryRowContext(ctx, upsertIncrementEvaluations, arg.UserID, arg.Month)
	var i Usage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.EvaluationsCount,
		&i.PdfsCount,
		&i.IngestionsCount,
	)
	return i, err
}

const upsertIncrementIngestions = `-- name: UpsertIncrementIngestions :one
INSERT INTO usage (user_id, month, ingestions_count)
VALUES ($1, $2, 1)
ON CONFLICT (user_id, month) DO UPDATE
  SET ingestions_count = usage.ingestions_count + 1
RETURNING id, user_id, month, evaluations_count, pdfs_count, ingestions_count
`

type UpsertIncrementIngestionsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Month  string    `json:"month"`
}

func (q *Queries) UpsertIncrementIngestions(ctx context.Context, arg UpsertIncrementIngestionsParams) (Usage, error) {
	row := q.db.QueryRowContext(ctx, upsertIncrementIngestions, arg.UserID, arg.Month)
	var i Usage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.EvaluationsCount,
		&i.PdfsCount,
		&i.IngestionsCount,
	)
	return i, err
}

const upsertIncrementPDFs = `-- name: UpsertIncrementPDFs :one
INSERT INTO usage (user_id, month, pdfs_count)
VALUES ($1, $2, 1)
ON CONFLICT (user_id, month) DO UPDATE
  SET pdfs_count = usage.pdfs_count + 1
RETURNING id, user_id, month, evaluations_count, pdfs_count, ingestions_count
`

type UpsertIncrementPDFsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Month  string    `json:"month"`
}

func (q *Queries) UpsertIncrementPDFs(ctx context.Context, arg UpsertIncrementPDFsParams) (Usage, error) {
	row := q.db.QueryRowContext(ctx, upsertIncrementPDFs, arg.UserID, arg.Month)
	var i Usage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.EvaluationsCount,
		&i.PdfsCount,
		&i.IngestionsCount,
	)
	return i, err
}
