// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const dropProfileOverrideKey = `-- name: DropProfileOverrideKey :one
UPDATE users
SET profile_overrides = profile_overrides - $2::text
WHERE id = $1
RETURNING profile_overrides
`

type DropProfileOverrideKeyParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 string    `json:"column_2"`
}

func (q *Queries) DropProfileOverrideKey(ctx context.Context, arg DropProfileOverrideKeyParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, dropProfileOverrideKey, arg.ID, arg.Column2)
	var profile_overrides json.RawMessage
	err := row.Scan(&profile_overrides)
	return profile_overrides, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, email, google_id, plan, cv_markdown, profile_json, profile_overrides, created_at, google_refresh_token FROM users
WHERE google_id = $1
LIMIT 1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Plan,
		&i.CvMarkdown,
		&i.ProfileJson,
		&i.ProfileOverrides,
		&i.CreatedAt,
		&i.GoogleRefreshToken,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, google_id, plan, cv_markdown, profile_json, profile_overrides, created_at, google_refresh_token FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Plan,
		&i.CvMarkdown,
		&i.ProfileJson,
		&i.ProfileOverrides,
		&i.CreatedAt,
		&i.GoogleRefreshToken,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT cv_markdown, profile_json, profile_overrides
FROM users WHERE id = $1 LIMIT 1
`

type GetUserProfileRow struct {
	CvMarkdown       sql.NullString  `json:"cv_markdown"`
	ProfileJson      json.RawMessage `json:"profile_json"`
	ProfileOverrides json.RawMessage `json:"profile_overrides"`
}

func (q *Queries) GetUserProfile(ctx context.Context, id uuid.UUID) (GetUserProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getUserProfile, id)
	var i GetUserProfileRow
	err := row.Scan(&i.CvMarkdown, &i.ProfileJson, &i.ProfileOverrides)
	return i, err
}

const setProfileOverrideKey = `-- name: SetProfileOverrideKey :one
UPDATE users
SET profile_overrides = profile_overrides || jsonb_build_object($2::text, $3::jsonb)
WHERE id = $1
RETURNING profile_overrides
`

type SetProfileOverrideKeyParams struct {
	ID      uuid.UUID       `json:"id"`
	Column2 string          `json:"column_2"`
	Column3 json.RawMessage `json:"column_3"`
}

func (q *Queries) SetProfileOverrideKey(ctx context.Context, arg SetProfileOverrideKeyParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, setProfileOverrideKey, arg.ID, arg.Column2, arg.Column3)
	var profile_overrides json.RawMessage
	err := row.Scan(&profile_overrides)
	return profile_overrides, err
}

const updateUserCVMarkdown = `-- name: UpdateUserCVMarkdown :one
UPDATE users
SET cv_markdown = $2
WHERE id = $1
RETURNING id, email, google_id, plan, cv_markdown, profile_json, profile_overrides, created_at, google_refresh_token
`

type UpdateUserCVMarkdownParams struct {
	ID         uuid.UUID      `json:"id"`
	CvMarkdown sql.NullString `json:"cv_markdown"`
}

func (q *Queries) UpdateUserCVMarkdown(ctx context.Context, arg UpdateUserCVMarkdownParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserCVMarkdown, arg.ID, arg.CvMarkdown)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Plan,
		&i.CvMarkdown,
		&i.ProfileJson,
		&i.ProfileOverrides,
		&i.CreatedAt,
		&i.GoogleRefreshToken,
	)
	return i, err
}

const updateUserGoogleRefreshToken = `-- name: UpdateUserGoogleRefreshToken :one
UPDATE users
SET google_refresh_token = $2
WHERE id = $1
RETURNING id, email, google_id, plan, cv_markdown, profile_json, profile_overrides, created_at, google_refresh_token
`

type UpdateUserGoogleRefreshTokenParams struct {
	ID                 uuid.UUID      `json:"id"`
	GoogleRefreshToken sql.NullString `json:"google_refresh_token"`
}

func (q *Queries) UpdateUserGoogleRefreshToken(ctx context.Context, arg UpdateUserGoogleRefreshTokenParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserGoogleRefreshToken, arg.ID, arg.GoogleRefreshToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Plan,
		&i.CvMarkdown,
		&i.ProfileJson,
		&i.ProfileOverrides,
		&i.CreatedAt,
		&i.GoogleRefreshToken,
	)
	return i, err
}

const updateUserPlan = `-- name: UpdateUserPlan :one
UPDATE users
SET plan = $2
WHERE id = $1
RETURNING id, email, google_id, plan, cv_markdown, profile_json, profile_overrides, created_at, google_refresh_token
`

type UpdateUserPlanParams struct {
	ID   uuid.UUID `json:"id"`
	Plan PlanT     `json:"plan"`
}

func (q *Queries) UpdateUserPlan(ctx context.Context, arg UpdateUserPlanParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPlan, arg.ID, arg.Plan)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Plan,
		&i.CvMarkdown,
		&i.ProfileJson,
		&i.ProfileOverrides,
		&i.CreatedAt,
		&i.GoogleRefreshToken,
	)
	return i, err
}
