// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, email, google_id, plan, cv_markdown, profile_json, created_at, google_refresh_token FROM users
WHERE google_id = $1
LIMIT 1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Plan,
		&i.CvMarkdown,
		&i.ProfileJson,
		&i.CreatedAt,
		&i.GoogleRefreshToken,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, google_id, plan, cv_markdown, profile_json, created_at, google_refresh_token FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Plan,
		&i.CvMarkdown,
		&i.ProfileJson,
		&i.CreatedAt,
		&i.GoogleRefreshToken,
	)
	return i, err
}

const updateUserCVMarkdown = `-- name: UpdateUserCVMarkdown :one
UPDATE users
SET cv_markdown = $2
WHERE id = $1
RETURNING id, email, google_id, plan, cv_markdown, profile_json, created_at, google_refresh_token
`

type UpdateUserCVMarkdownParams struct {
	ID         uuid.UUID      `json:"id"`
	CvMarkdown sql.NullString `json:"cv_markdown"`
}

func (q *Queries) UpdateUserCVMarkdown(ctx context.Context, arg UpdateUserCVMarkdownParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserCVMarkdown, arg.ID, arg.CvMarkdown)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Plan,
		&i.CvMarkdown,
		&i.ProfileJson,
		&i.CreatedAt,
		&i.GoogleRefreshToken,
	)
	return i, err
}

const updateUserGoogleRefreshToken = `-- name: UpdateUserGoogleRefreshToken :one
UPDATE users
SET google_refresh_token = $2
WHERE id = $1
RETURNING id, email, google_id, plan, cv_markdown, profile_json, created_at, google_refresh_token
`

type UpdateUserGoogleRefreshTokenParams struct {
	ID                 uuid.UUID      `json:"id"`
	GoogleRefreshToken sql.NullString `json:"google_refresh_token"`
}

func (q *Queries) UpdateUserGoogleRefreshToken(ctx context.Context, arg UpdateUserGoogleRefreshTokenParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserGoogleRefreshToken, arg.ID, arg.GoogleRefreshToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Plan,
		&i.CvMarkdown,
		&i.ProfileJson,
		&i.CreatedAt,
		&i.GoogleRefreshToken,
	)
	return i, err
}

const updateUserPlan = `-- name: UpdateUserPlan :one
UPDATE users
SET plan = $2
WHERE id = $1
RETURNING id, email, google_id, plan, cv_markdown, profile_json, created_at, google_refresh_token
`

type UpdateUserPlanParams struct {
	ID   uuid.UUID `json:"id"`
	Plan PlanT     `json:"plan"`
}

func (q *Queries) UpdateUserPlan(ctx context.Context, arg UpdateUserPlanParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPlan, arg.ID, arg.Plan)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Plan,
		&i.CvMarkdown,
		&i.ProfileJson,
		&i.CreatedAt,
		&i.GoogleRefreshToken,
	)
	return i, err
}

const updateUserProfileJSON = `-- name: UpdateUserProfileJSON :one
UPDATE users
SET profile_json = $2
WHERE id = $1
RETURNING id, email, google_id, plan, cv_markdown, profile_json, created_at, google_refresh_token
`

type UpdateUserProfileJSONParams struct {
	ID          uuid.UUID       `json:"id"`
	ProfileJson json.RawMessage `json:"profile_json"`
}

func (q *Queries) UpdateUserProfileJSON(ctx context.Context, arg UpdateUserProfileJSONParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfileJSON, arg.ID, arg.ProfileJson)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Plan,
		&i.CvMarkdown,
		&i.ProfileJson,
		&i.CreatedAt,
		&i.GoogleRefreshToken,
	)
	return i, err
}
