// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watched_companies.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteWatchedCompany = `-- name: DeleteWatchedCompany :exec
DELETE FROM watched_companies
WHERE id = $1
`

func (q *Queries) DeleteWatchedCompany(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWatchedCompany, id)
	return err
}

const getWatchedCompanyByID = `-- name: GetWatchedCompanyByID :one
SELECT id, user_id, name, careers_url, provider_id, ats_api_url, enabled, company_id, created_at FROM watched_companies
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetWatchedCompanyByID(ctx context.Context, id uuid.UUID) (WatchedCompany, error) {
	row := q.db.QueryRowContext(ctx, getWatchedCompanyByID, id)
	var i WatchedCompany
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CareersUrl,
		&i.ProviderID,
		&i.AtsApiUrl,
		&i.Enabled,
		&i.CompanyID,
		&i.CreatedAt,
	)
	return i, err
}

const insertWatchedCompany = `-- name: InsertWatchedCompany :one
INSERT INTO watched_companies (
  user_id,
  name,
  careers_url,
  provider_id,
  ats_api_url,
  enabled,
  company_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, name, careers_url, provider_id, ats_api_url, enabled, company_id, created_at
`

type InsertWatchedCompanyParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	Name       string         `json:"name"`
	CareersUrl sql.NullString `json:"careers_url"`
	ProviderID sql.NullString `json:"provider_id"`
	AtsApiUrl  sql.NullString `json:"ats_api_url"`
	Enabled    bool           `json:"enabled"`
	CompanyID  uuid.NullUUID  `json:"company_id"`
}

func (q *Queries) InsertWatchedCompany(ctx context.Context, arg InsertWatchedCompanyParams) (WatchedCompany, error) {
	row := q.db.QueryRowContext(ctx, insertWatchedCompany,
		arg.UserID,
		arg.Name,
		arg.CareersUrl,
		arg.ProviderID,
		arg.AtsApiUrl,
		arg.Enabled,
		arg.CompanyID,
	)
	var i WatchedCompany
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CareersUrl,
		&i.ProviderID,
		&i.AtsApiUrl,
		&i.Enabled,
		&i.CompanyID,
		&i.CreatedAt,
	)
	return i, err
}

const listEnabledWatchedCompaniesByUser = `-- name: ListEnabledWatchedCompaniesByUser :many
SELECT id, user_id, name, careers_url, provider_id, ats_api_url, enabled, company_id, created_at FROM watched_companies
WHERE user_id = $1
  AND enabled = true
ORDER BY created_at DESC
`

func (q *Queries) ListEnabledWatchedCompaniesByUser(ctx context.Context, userID uuid.UUID) ([]WatchedCompany, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledWatchedCompaniesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WatchedCompany
	for rows.Next() {
		var i WatchedCompany
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CareersUrl,
			&i.ProviderID,
			&i.AtsApiUrl,
			&i.Enabled,
			&i.CompanyID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchedCompaniesByUser = `-- name: ListWatchedCompaniesByUser :many
SELECT id, user_id, name, careers_url, provider_id, ats_api_url, enabled, company_id, created_at FROM watched_companies
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWatchedCompaniesByUser(ctx context.Context, userID uuid.UUID) ([]WatchedCompany, error) {
	rows, err := q.db.QueryContext(ctx, listWatchedCompaniesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WatchedCompany
	for rows.Next() {
		var i WatchedCompany
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CareersUrl,
			&i.ProviderID,
			&i.AtsApiUrl,
			&i.Enabled,
			&i.CompanyID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
